# 라이브러리 응용

In [ ]:
#쓰레드 제어 준비
import time as t

# 작업 5초
def long_task():
    for w in range(5):
        print(f"일하는 중...{w+1}")
        t.sleep(1)

In [28]:
#쓰레드 제어
#작업 5초 x 5회 = 25초

start = t.time()
print("=====Start=====")
for n in range(5):
    long_task()
print("=====End=====")
print(f"총 소요 시간: {t.time() - start:.2f}초")

=====Start=====
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
=====End=====
총 소요 시간: 25.03초


In [ ]:
# 쓰레드를 사용함, 프로그램적으로(논리적) 병렬처리
import threading
import time as t
start = t.time()
print("=====Start=====")
threads = []
for n in range(5):
    th = threading.Thread(target=long_task)
    threads.append(th)    
for tr in threads:
    tr.start()
for tr in threads:
    tr.join()
print("=====End=====")
print(f"총 소요 시간: {t.time() - start:.2f}초")

In [32]:
# multiprocessing 라이브러리 사용 물리적 cpu 코어를 활용하여 병렬처리
import multiprocessing
import time as t
def long_task():
    for w in range(5):
        print(f"일하는 중...{w+0.5}")
        t.sleep(0.5)


if __name__ == "__main__":
    start = t.time()
    print("=====start=====")
    processes = []
    for n in range(5):
        p = multiprocessing.Process(target=long_task)
        processes.append(p)    
    for p in processes:
        p.start()
    for p in processes:
        p.join()
    print("=====End=====")
    print(f"총 소요 시간: {t.time() - start:.2f}초")

=====start=====
=====End=====
총 소요 시간: 0.06초


# JSON

In [38]:
test = {"name": "홍길동",
		"age": 30,
		"address": "부산"}

print(type(test), test)

<class 'dict'> {'name': '홍길동', 'age': 30, 'address': '부산'}


In [41]:
import json
#json으로 변환

data =json.dumps(test,ensure_ascii=False) #문자열로 변환
print(type(data),data)


<class 'str'> {"name": "홍길동", "age": 30, "address": "부산"}


In [54]:
#스마트카 데이터 json 파일 만들기
import json
import time

def generate_smartcar_data():
    import random
    return {
        "car_id": random.randint(1, 100),
        "speed": random.uniform(0, 150),
        "fuel_level": random.uniform(0, 100),
        "longitude": round(random.uniform(-180, 180), 6),
        "latitude": round(random.uniform(-90, 90), 6),
        "timestamp": time.time()
    }

with open("smartcar_data.json","w") as file:
    for _ in range(100): # 100개의 데이터 생성
        data =generate_smartcar_data()
        json.dump(data,file)
        file.write("\n")
    print("스마트카 데이터가 smartcar_data.json 파일에 저장되었습니다")

스마트카 데이터가 smartcar_data.json 파일에 저장되었습니다


In [59]:
with open("smartcar_data.json", "r") as f:
    data = [json.loads(line) for line in f]
print(data[:5])  # 처음 5개의 데이터 출력

[{'car_id': 10, 'speed': 98.48740099664622, 'fuel_level': 54.849071059086526, 'longitude': 23.729889, 'latitude': 80.811404, 'timestamp': 1752028585.0548205}, {'car_id': 83, 'speed': 107.24600555703638, 'fuel_level': 22.84777722903111, 'longitude': -115.014249, 'latitude': -70.111247, 'timestamp': 1752028585.0548532}, {'car_id': 60, 'speed': 78.63087043221985, 'fuel_level': 70.5747476878966, 'longitude': -99.889703, 'latitude': -85.874376, 'timestamp': 1752028585.054869}, {'car_id': 33, 'speed': 47.42907774578269, 'fuel_level': 66.18344964993892, 'longitude': -132.997189, 'latitude': -39.870188, 'timestamp': 1752028585.0548851}, {'car_id': 97, 'speed': 63.13491261658714, 'fuel_level': 85.03892385673187, 'longitude': 67.116311, 'latitude': 15.438704, 'timestamp': 1752028585.054896}]


In [60]:
for d in data:
    if d.get("car_id") ==77:
        print(d)

{'car_id': 77, 'speed': 114.31663732393262, 'fuel_level': 32.96448934968327, 'longitude': -99.377882, 'latitude': 8.364583, 'timestamp': 1752028585.0560424}


In [65]:
import requests
#import json 주석처리해도  밑의 .json() 제대로 작동한다 requests에 포함되어있는기능이기디떄문

ur1 ="https://jsonplaceholder.typicode.com/posts"

data =requests.get(ur1).json()
for d in data:
    if d.get("id") ==77:
        print(d["id"],d["title"])


77 necessitatibus quasi exercitationem odio


In [80]:
import requests
ur1 ="https://jsonplaceholder.typicode.com/posts"

f = open("test.text", "w", encoding="utf-8")
data = requests.get(ur1).json()

for d in data:
    if 50 <= d.get("id") <= 70:
        f.write(d["title"] + "\n")
f.close()

f = open("test.text", "r", encoding="utf-8")  # 파일 열기 (읽기 모드)
contents = f.read()                        #(2) 할경우 2바이트 읽기
print(contents)  # 파일 내용 출력
f.close()  # 파일 닫기

repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem
soluta aliquam aperiam consequatur illo quis voluptas
qui enim et consequuntur quia animi quis voluptate quibusdam
ut quo aut ducimus alias
sit asperiores ipsam eveniet odio non quia
sit vel voluptatem et non libero
qui et at rerum necessitatibus
sed ab est est
voluptatum itaque dolores nisi et quasi
qui commodi dolor at maiores et quis id accusantium
consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere
voluptatem doloribus consectetur est ut ducimus
beatae enim quia vel
voluptas blanditiis repellendus animi ducimus error sapiente et suscipit
et fugit quas eum in in aperiam quod
consequatur id enim sunt et et
repudiandae ea animi iusto
aliquid eos sed fuga est maxime repellendus
odio quis facere architecto reiciendis optio
fugiat quod pariatur odit minima
voluptatem laborum magni



In [86]:
import requests as req
from bs4 import BeautifulSoup as bs
un1 = "https://finance.naver.com/sise/sise_market_sum.nhn"
web = req.get(un1)

soup = bs(web.content, "html.parser")
#print(soup.title.text) #페이지 제목출력
tableline = soup.select(".type_2 tr")

for t in tableline:
    no = t.select_one(".no")
    title = t.select_one(".tltle")
    number = t.select_one(".number")
    if (no or title or number):
        if int(number.text.replace(",", "")) < 40000:
            print(no.text if no else "", title.text if title else "", int(str(number.text).replace(",", "")) if number else "")

20 HMM 24650
22 한국전력 37400
29 우리금융지주 25300
36 기업은행 20150
38 삼성중공업 17725
39 카카오뱅크 30300
45 미래에셋증권 21850


In [96]:
!pip install -q -U google-genai

In [110]:
from google import genai
def aiai(text):
    client = genai.Client(api_key="AIzaSyBpQ5XC5O0j-pmvVa2YHInur6zc2yweuIc")
    response = client.models.generate_content(
    model="gemini-2.5-flash", contents= text + ";단, 300자 이내로 서술형으로 친절하게 설명해줘,스마트제조,스마트팜"
)
print(response.text)

aiai("시퀀스에 대해 설명해줘.")

OpenAI와 연동(통합)하는 방법은 주로 OpenAI가 제공하는 **API(Application Programming Interface)**를 사용하는 것을 의미합니다. 이를 통해 여러분의 프로그램, 웹사이트, 서비스 등에서 OpenAI의 강력한 AI 모델(GPT-4, GPT-3.5 Turbo, DALL-E 3, Whisper 등)의 기능을 활용할 수 있습니다.

가장 일반적이고 권장되는 방법은 **공식 라이브러리(Python, Node.js 등)**를 사용하는 것이며, 여기서는 가장 많이 사용되는 **Python**을 기준으로 설명해 드리겠습니다.

---

### OpenAI API 연동 기본 단계

#### 1. 필수 준비물

1.  **OpenAI 계정 생성:**
    *   OpenAI 웹사이트(platform.openai.com)에 접속하여 회원가입을 합니다.
    *   API를 사용하려면 결제 정보(신용카드)를 등록해야 할 수 있습니다. (무료 크레딧이 소진되거나 유료 모델을 사용할 경우)

2.  **API Key 발급 (매우 중요!):**
    *   로그인 후, 우측 상단 프로필 아이콘을 클릭하여 "API keys" 메뉴로 이동합니다.
    *   "Create new secret key" 버튼을 클릭하여 새 API Key를 발급받습니다.
    *   **발급받은 키는 다시 볼 수 없으므로, 반드시 안전한 곳에 복사하여 보관해야 합니다.** 이 키는 여러분의 계정을 사용하여 OpenAI API에 접근하는 비밀번호와 같으므로, 절대 외부에 노출되어서는 안 됩니다.

3.  **프로그래밍 환경 준비:**
    *   Python이 설치되어 있어야 합니다. (Python 3.7 이상 권장)
    *   선택적으로, 가상 환경(virtual environment)을 설정하여 프로젝트 종속성을 관리하는 것이 좋습니다.

---

#### 2. Python을 이용한 API 연동 (기본 예시: 챗봇)

Python용 OpenAI 라이브러리

In [115]:
from google import genai

client = genai.Client(api_key="AIzaSyBpQ5XC5O0j-pmvVa2YHInur6zc2yweuIc")  # 전역에서 1회만 생성

def aiai(text):
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=(
            text
            + ";단, 300자 이내로 서술형으로 친절하게 설명해줘, 스마트제조, 스마트팜"
        )
    )
    print(response.text)          # 함수 내부로 들여쓰기

aiai("시퀀스에 대해 설명해줘.")

안녕하세요! 시퀀스란 **어떤 작업이나 동작들이 정해진 순서대로 실행되도록 나열한 것**을 말해요. 마치 요리 레시피처럼, 각 단계가 순서대로 진행되어야 원하는 결과가 나오는 것과 같아요.

**스마트제조**에서는 제품 생산의 각 단계, 예를 들어 부품 조립, 검사, 포장 등이 정해진 순서대로 진행되어야 생산 효율을 높일 수 있죠. **스마트팜**에서는 작물 생장에 필요한 물 공급, 영양분 투입, 조명 조절 등이 정해진 시간에 맞춰 순차적으로 이루어져 최적의 재배 환경을 만듭니다.

시퀀스는 복잡한 시스템을 자동화하고 효율적으로 제어하는 데 핵심적인 역할을 한답니다.


In [101]:
!pip install openai

   ---------------------------------------- 0.0/755.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/755.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/755.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/755.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? eta -:--:--
   ------------- -------------------------- 262.1/755.1 kB ? 

In [160]:
from openai import OpenAI

client = OpenAI(
    api_key="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"  # 실제 키 입력
)
#돈내면 사용가능 들어가서 구매해야함
completion = client.chat.completions.create(
    model="gpt-4o-mini",   # 또는 "gpt-3.5-turbo", "gpt-4o"
    messages=[
        {"role": "user", "content": "무료로안돼?"}
    ]
)

print(completion.choices[0].message.content)

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [118]:
!pip install qrcode

In [122]:
!pip install pillow

   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   --- ------------------------------------ 0.5/7.0 MB 230.9 kB/s eta 0:00:28
   --- ------------------------------------ 0.5/7.0 MB 230.9 kB/s eta 0:00:28
   --- ------------------------------------ 0.5/7.0 MB 230.9 kB/s eta 0:00:28
   --- ------------------------------------ 0.5/7.0 MB 230.9 kB/s eta 0:00:28
   --- ------------------------------------ 0.5/7.0 MB 230.9 kB/s e

In [ ]:
import qrcode

def qrcode_maker(text, filename="rq.png"):
    qr = qrcode.make(text)
    qr.save(filename)     # 이미지 저장
    return text          # 셀 하단에 문자열이 표시됨

qrcode_maker("안녕하세요. 이것은 QR 코드입니다.")

#넘파이 Numpy

In [6]:
#numpy
import numpy as np
data1 =[1,2,3,4,5]
data2 =[1,2,3,4,5,6]

In [7]:
arr1 =np.array(data1)
arr2 =np.array(data2)
arr1,arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [8]:
arr1.shape ,arr1.dtype  

((5,), dtype('int64'))

In [ ]:
arr3 =np.array([[1,2,3],[4,5,6]])  
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
arr3.shape , arr3.dtype

((2, 3), dtype('int64'))

In [152]:
zz =np.zeros(10)
zz, zz.shape ,zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [ ]:
zzz = np.zeros((3,5))   ##3개의 상위 5개의 담겼다.
zzz, zzz.shape, zzz.dtype  

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])


# np.array 연산

In [35]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [36]:
arr1.shape , arr1.dtype
arr2.shape , arr2.dtype

((2, 3), dtype('int64'))

In [37]:
result0 = arr1*3
result1 = arr1 + arr2
result2 = arr1 - arr2  
result3 = arr1*2 - arr2/10  
result4 = arr1 * arr2  
result5 = arr1 / arr2

#브로드캐스트: 같은 크기의 배열을 가지지않아도 요소별 연산이 가능함
arr3 = np.array([22,33,44])

print(arr1+arr3)  
print(result0)  
print(result1)  
print(result2)  
print(result3)  
print(result4)  
print(result5)  

[[23 35 47]
 [26 38 50]]
[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]


In [ ]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의 개수
arr = np.arange(5)
arr, arr.shape, arr.dtype, arr.size, arr.ndim

In [11]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,'a','b'])
arr3 = np.array([1,2,3,4],dtype='str')
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3 4] int64
['1' '2' '3' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [ ]:
arr4 = np.full((4,3),"없어요")
print(arr4)
arr5 = np.eye(6)
print(arr5)
arr6 = np.linspace(0,300,15,endpoint=False) #15등분으로 나눠는방법 end포인트경우 마지막거에 거짓이라하면 안나오게할수있다.
print(arr6)
arr7 =np.arange(0,100,20)
print(arr7)

[['없어요' '없어요' '없어요']
 ['없어요' '없어요' '없어요']
 ['없어요' '없어요' '없어요']
 ['없어요' '없어요' '없어요']]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180. 200. 220. 240. 260.
 280.]
[ 0 20 40 60 80]


## 2차원

In [39]:
try:
    arr21 =np.arange(1,10).reshape(3,3)
    print(arr21, arr21.shape,arr21.size, arr21.dtype,arr21.ndim, type(arr21))
    arr21 =np.arange(1,11).reshape(2,5)
    print(arr21, arr21.shape,arr21.size, arr21.dtype,arr21.ndim, type(arr21))
    arr21 =np.arange(1,19).reshape(3,6)
    print(arr21, arr21.shape,arr21.size, arr21.dtype,arr21.ndim, type(arr21))

except ValueError as e:
    print("차원과 사이즈가 맞지 않아요:",e)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] (3, 6) 18 int64 2 <class 'numpy.ndarray'>
